# PrivilegeStorage plugin configuration

server: global # For server networks

database: # MySQL

  host: localhost
  port: 3306
  database: database
  table: privilege

  user: root
  password: 'password'

  # Pool settings
  maximumPoolSize: 10
  connectionTimeout: 30000
  idleTimeout: 60000
  maxLifetime: 60000


luckperms:
  exclude: '' # If you don't want PrivilegeStorage to manage any privileges, add their names here (separate with space)

messages:

  placeholders:
    prefix: '%PREFIX%'
    player: '%PLAYER%'
    player2: '%PLAYER2%'
    privilege: '%PRIV%'
    count: '%COUNT%'

  prefix: '&bPrivileges &8>>'

  help:
    - '%PREFIX% &7Privilege help:'
    - '%PREFIX%   &7Show this message&8: &6/privilege help'
    - '%PREFIX%   &7View your privileges&8: &6/privilege list'
    - '%PREFIX%   &7Give privilege to another player&8: &6/privilege give <player> <type>'

  reloaded: '%PREFIX% &aConfiguration reloaded!'

  player-not-found: '%PREFIX% &cPlayer not found'
  unknown-command: '%PREFIX% &cUnknown command'
  unknown-privilege-type: '%PREFIX% &cUnknown privilege type'
  no-permission: '%PREFIX% &cYou don''t have permission to execute this command'
  invalid-arguments: '%PREFIX% &cInvalid number of arguments'
  invalid-count: '%PREFIX% &cInvalid amount'
  you-have-not-enough-privileges: '%PREFIX% &cYou don''t have enough privileges of this type'
  player-has-not-enough-privileges: '%PREFIX% &cPlayer &b%PLAYER% &cdoesn''t have enough privileges of this type'
  you-cant-give-used-privilege: '%PREFIX% &cYou cannot give a privilege that is in use'
  you-now-have-privileges: '%PREFIX% &aYou now have &b%COUNT% &aprivileges of type &b%PRIV%'
  you-gave-privilege: '%PREFIX% &aYou gave &b%PRIV% &aprivilege to &b%PLAYER%'
  player-gave-privilege: '%PREFIX% &aYou received &b%PRIV% &aprivilege from &b%PLAYER%'
  you-set-privilege: '%PREFIX% &aYou set &b%PRIV% &aprivilege for &b%PLAYER% &ato amount &b%COUNT%'
  admin-set-privilege: '%PREFIX% &aAdministrator &b%PLAYER% &aset your &b%PRIV% &aprivilege to amount &b%COUNT%'
  you-added-privilege: '%PREFIX% &aYou added &b%PRIV% &aprivilege to &b%PLAYER% &awith amount &b%COUNT%'
  admin-added-privilege: '%PREFIX% &aAdministrator &b%PLAYER% &aadded &b%PRIV% &aprivilege to you with amount &b%COUNT%'
  you-took-privilege: '%PREFIX% &aYou took &b%PRIV% &aprivilege from &b%PLAYER% &awith amount &b%COUNT%'
  admin-took-privilege: '%PREFIX% &aAdministrator &b%PLAYER% &atook your &b%PRIV% &aprivilege with amount &b%COUNT%'
  you-have-header: '%PREFIX% &aYour privileges&8:'
  you-have-privilege: '%PREFIX%   &b%PRIV% &8: &b%COUNT% pcs'
  player-has-header: '%PREFIX% &aPlayer &b%PLAYER%&a''s privileges&8:'
  player-has-privilege: '%PREFIX%   &b%PRIV% &8: &b%COUNT% pcs'
  you-reset-privilege: '%PREFIX% &aYou reset all privileges for %PLAYER%'

  usage-give: '%PREFIX% &6/priv give <player> <privilege>'
  usage-set: '%PREFIX% &6/priv set <player> <privilege> <amount>'
  usage-add: '%PREFIX% &6/priv add <player> <privilege> <amount>'
  usage-take: '%PREFIX% &6/priv take <player> <privilege> <amount>'

  give:
    - ''
    - '%PREFIX% &aPlayer &b%PLAYER% &agave &b%PRIV% &aprivilege to &b%PLAYER2%'
    - ''